blank_issues_enabled: false

contact_links:
  - name: [Discussions] 讨论区
    url: https://github.com/2dust/v2rayN/discussions
    about: 一般问题或使用建议请前往 Discussions。
  - name: [Wiki] 使用说明
    url: https://github.com/2dust/v2rayN/wiki
    about: 查看常见问题和使用文档。
